## Numpy

In [ ]:
# NumPy is a fundamental package for scientific computing in Python.
# It provides support for large, multi-dimensional arrays and matrices,
# along with a collection of mathematical functions to operate on these arrays efficiently.

import numpy as np

# Example: create a NumPy array
arr = np.array([1, 2, 3, 4, 5])
print("NumPy Array:", arr)

In [3]:
## Install numpy library using requirement.txt or using this

!pip install numpy

In [4]:
import numpy as np
## create array using numpy

## create 1D array
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [12]:
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5)  ## two dimension array -> 1 row and 5 col

array([[1, 2, 3, 4, 5]])

In [15]:
arr2 = np.array([[1,2,3,4,5]])
arr2.shape

(1, 5)

In [18]:
## 2D array..
arr2 = np.array([[1,2,3,4,5], [2,3,4,5,6]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [20]:
## Inbuild method..
np.arange(0, 10, 2).reshape(5, 1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [24]:
## Inbuilt method
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [26]:
## identity matrix..  -> all diagonal element is 1 only
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [30]:
## Attributes of numpy

arr1 = np.array([[1,2,3,4,5], [1,2,3,4,5]])

print(arr1)
print("Shape : ",arr1.shape)
print("Number of dimension : ", arr1.ndim)
print("Size(number of elements): ", arr1.size)
print("Data type: ", arr1.dtype)
print("Item size(in bytes): ", arr1.itemsize)

[[1 2 3 4 5]
 [1 2 3 4 5]]
Shape :  (2, 5)
Number of dimension :  2
Size(number of elements):  10
Data type:  int64
Item size(in bytes):  8


In [33]:
## Numpy vectorized operation

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20, 30, 40, 50])

# addition
print("Addition :", arr1+arr2)

## substraction
print("Substriction :", arr1+arr2)

## Multiplication
print("Multiplication :", arr1*arr2)

## Division
print("Division :", arr1/arr2)

Addition : [11 22 33 44 55]
Substriction : [11 22 33 44 55]
Multiplication : [ 10  40  90 160 250]
Division : [0.1 0.1 0.1 0.1 0.1]


In [36]:
## Universal function
arr1 = np.array([1,2,3,4,5])

# square root
print(np.sqrt(arr1))

# exponential
print(np.exp(arr1))

## sine
print(np.sin(arr1))

## natural log
print(np.log(arr1))

[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [38]:
## slicing operation

arr = np.array([[1,2,3,4,5], [6,7, 8, 9, 10], [11,12,13,14,15]])

print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [47]:
arr[1:, 1:4]

array([[ 7,  8,  9],
       [12, 13, 14]])

In [49]:
arr[1:, 3:]

array([[ 9, 10],
       [14, 15]])

In [51]:
## modify the arr
arr[0, 0] = 100
arr

array([[100,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15]])

In [53]:
arr[1:, 2:] = 100
arr

array([[100,   2,   3,   4,   5],
       [  6,   7, 100, 100, 100],
       [ 11,  12, 100, 100, 100]])

In [5]:
## statistical concepts -> Normalization
## to have a mean of 0 and standard deviation of 1

data = np.array([1,2,3,4,5])

# calculate the mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

## Normalize the data
normalize_data = (data-mean)/std_dev
print("Normalize data :", normalize_data)

Normalize data : [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [6]:
## statistical concepts
data = np.array([1,2,3,4,5])

## mean
mean = np.mean(data)
print("Mean : ", mean)

std_dev = np.std(data)
print("Standard deviation : ", std_dev)

median = np.median(data)
print("Median : ", median)

variance = np.var(data)
print("Variance : ", variance)

Mean :  3.0
Standard deviation :  1.4142135623730951
Median :  3.0
Variance :  2.0


In [11]:
## Logical operations

arr = np.array([1,2,3,4,5,6,7,8,9])

arr[(arr <= 8) & (arr >= 3)]

array([3, 4, 5, 6, 7, 8])